date.timezone = Asia/Shanghai
memory_limit = 512M
max_execution_time = 3600
max_input_time = 3600
post_max_size = 10G
upload_max_filesize = 10G
max_file_uploads = 200
file_uploads = On
allow_url_fopen = On
expose_php = Off
display_errors = Off
log_errors = On
session.cookie_httponly = On
session.cookie_samesite = Lax
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 192
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2
